# Use root/example as user/password credentials
version: "3.9"

# Sets the project name.
name: localhost-databases

services:
  mongo:
    image: mongo:latest
    container_name: "${DB_CONTAINER_NAME:-mongodb}"
    environment:
      MONGO_INITDB_DATABASE: "${DB_DATABASE:-local}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      retries: 3
      timeout: 5s
    networks:
      - local
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db

# The Docker networks.
networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
  mongodb_config:
    driver: "local"
    name: "${DB_VOLUME_CONFIG_NAME:-mongodb_config}"
  mongodb_data:
    driver: "local"
    name: "${DB_VOLUME_DATA_NAME:-mongodb_data}"
